-- 1. 오버나이트 스크리닝 마스터 테이블
CREATE TABLE IF NOT EXISTS public.overnight_screening_records (
    date text PRIMARY KEY,                       -- YYYYMMDD (KST)
    reduce_weight boolean DEFAULT false NOT NULL, -- 비중 축소 제안 여부
    kosdaq_value numeric DEFAULT 0 NOT NULL,     -- 코스닥 지수 종가
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. 오버나이트 스크리닝 종목 상세 테이블
CREATE TABLE IF NOT EXISTS public.overnight_screening_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text REFERENCES public.overnight_screening_records(date) ON DELETE CASCADE NOT NULL,
    symbol text NOT NULL,                        -- 종목코드 (예: 005930)
    name text NOT NULL,                          -- 종목명 (예: 삼성전자)
    classification text NOT NULL,                -- 분류 (normal, aggressive, exclude, excludedNotice)
    entry_close numeric DEFAULT 0 NOT NULL,      -- 진입 종가
    reasons text[] DEFAULT '{}'::text[] NOT NULL, -- 선정/제외 사유 목록
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    
    CONSTRAINT unique_date_symbol UNIQUE (date, symbol)
);

-- 인덱스 추가 (조회 최적화)
CREATE INDEX IF NOT EXISTS idx_screening_items_date ON public.overnight_screening_items(date);
CREATE INDEX IF NOT EXISTS idx_screening_items_symbol ON public.overnight_screening_items(symbol);
